name: Generate Radar GIF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARTOPY_USER_BACKEND: ${{ github.workspace }}/cartopy_data
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.0"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies from requirements.txt
        run: python -m pip install -r requirements.txt

      - name: Determine current UTC date
        id: date
        run: |
          UTC_DATE=$(date -u +"%Y_%m_%d")
          echo "UTC_DATE=$UTC_DATE" >> $GITHUB_ENV
          echo "Current UTC date: $UTC_DATE"

      - name: Ensure output folder exists
        run: mkdir -p nexrad

      - name: Run radar script
        run: python radar_script.py ${{ env.UTC_DATE }}

      - name: Upload GIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: radar-gif
          path: nexrad/MOB_N0B_${{ env.UTC_DATE }}*.gif



