name: Generate Radar GIF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARTOPY_USER_BACKEND: ${{ github.workspace }}/cartopy_data
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary pyart metpy cartopy matplotlib pillow requests beautifulsoup4

      - name: Determine current UTC date
        id: date
        run: |
          UTC_DATE=$(date -u +"%Y_%m_%d")
          echo "UTC_DATE=$UTC_DATE" >> $GITHUB_ENV
          echo "UTC_DATE=$UTC_DATE"

      - name: Run radar script
        run: |
          mkdir -p nexrad
          python radar_script.py $UTC_DATE
          
      - name: Upload GIF artifact
        uses: actions/upload-artifact@v3
        with:
          name: radar-gif
          path: MOB_N0B_${{ env.UTC_DATE }}*.gif
